#!/usr/bin/env node
/**
 * Scan codebase-wiki/{architecture,discussion,issue,reference,roadmap}/*.md for frontmatter
 * `id` + `title`, then rewrite .vitepress/sidebar.generated.mts.
 *
 * Usage: node regenerate-sidebar.mjs --root <project-root>
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const WIKI_DIR = "codebase-wiki";

const CATEGORIES = [
  { dir: "architecture", group: "架构分析", nav: "架构分析" },
  { dir: "discussion", group: "技术讨论", nav: "技术讨论" },
  { dir: "issue", group: "Issue 记录", nav: "Issue 记录" },
  { dir: "reference", group: "参考手册", nav: "参考手册" },
  { dir: "roadmap", group: "规划路线", nav: "开发规划" },
];

function parseArgs(argv) {
  const out = { root: process.cwd() };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--root" && argv[i + 1]) {
      out.root = path.resolve(argv[++i]);
    }
  }
  return out;
}

function readFrontmatter(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return null;
  const block = m[1];
  const map = {};
  for (const line of block.split(/\r?\n/)) {
    const lm = line.match(/^([\w-]+):\s*(.*)$/);
    if (lm) map[lm[1]] = lm[2].trim();
  }
  return map;
}

function idSortKey(id) {
  const s = String(id || "");
  const m = s.match(/^([ADIRP])-(\d{3})$/);
  if (!m) return [999, s];
  const prefixOrder = { A: 0, D: 1, I: 2, R: 3, P: 4 };
  return [prefixOrder[m[1]] ?? 50, Number(m[2], 10)];
}

function compareById(a, b) {
  const ka = idSortKey(a.id);
  const kb = idSortKey(b.id);
  if (ka[0] !== kb[0]) return ka[0] - kb[0];
  if (typeof ka[1] === "number" && typeof kb[1] === "number")
    return ka[1] - kb[1];
  return String(ka[1]).localeCompare(String(kb[1]));
}

function main() {
  const { root } = parseArgs(process.argv);
  const wikiRoot = path.join(root, WIKI_DIR);
  const vpDir = path.join(root, ".vitepress");
  const outFile = path.join(vpDir, "sidebar.generated.mts");

  if (!fs.existsSync(wikiRoot)) {
    console.error(`Missing wiki directory: ${wikiRoot}`);
    process.exit(1);
  }

  if (!fs.existsSync(vpDir)) {
    console.error(`Missing .vitepress directory: ${vpDir}`);
    process.exit(1);
  }

  /** @type {Record<string, Array<{ text: string; items: Array<{ text: string; link: string }> }>>} */
  const sidebar = {};

  /** @type {Array<{ text: string; link: string }>} */
  const nav = [{ text: "首页", link: "/INDEX" }];

  for (const { dir, group, nav: navLabel } of CATEGORIES) {
    const dirPath = path.join(wikiRoot, dir);
    const items = [];
    if (fs.existsSync(dirPath)) {
      const names = fs
        .readdirSync(dirPath)
        .filter((n) => n.endsWith(".md"))
        .sort();
      const metas = [];
      for (const name of names) {
        const fp = path.join(dirPath, name);
        const fm = readFrontmatter(fp);
        if (!fm || !fm.id) continue;
        const base = name.replace(/\.md$/i, "");
        const link = `/${dir}/${base}`;
        const title = fm.title || fm.id;
        metas.push({ id: fm.id, text: `${fm.id} ${title}`, link });
      }
      metas.sort(compareById);
      for (const row of metas) {
        items.push({ text: row.text, link: row.link });
      }
    }
    sidebar[`/${dir}/`] = [{ text: group, items }];
    if (items.length > 0) {
      nav.push({ text: navLabel, link: items[0].link });
    }
  }

  const banner =
    "// Auto-generated by skills/codebase-wiki/scripts/regenerate-sidebar.mjs\n" +
    "// Do not edit by hand; re-run the script after adding or renaming docs.\n\n" +
    "// @ts-nocheck\n\n";

  const body =
    `export const wikiSidebar = ${JSON.stringify(sidebar, null, 2)};\n\n` +
    `export const wikiNav = ${JSON.stringify(nav, null, 2)};\n`;

  fs.writeFileSync(outFile, banner + body, "utf8");
  console.log(`Wrote ${path.relative(root, outFile)}`);
}

main();
