// Auto-generated by skills/codebase-wiki/scripts/regenerate-sidebar.mjs
// Do not edit by hand; re-run the script after adding or renaming docs.

// @ts-nocheck

export const wikiSidebar = {
  "/architecture/": [
    {
      "text": "架构分析",
      "items": [
        {
          "text": "A-001 AI Native Editor 目标架构",
          "link": "/architecture/20260519-ai-native-editor-architecture"
        },
        {
          "text": "A-002 React Tapable Editor 设计理念",
          "link": "/architecture/20260519-design-philosophy"
        }
      ]
    }
  ],
  "/discussion/": [
    {
      "text": "技术讨论",
      "items": [
        {
          "text": "D-001 编辑器内核选型调研：Lexical、Tiptap 与 Draft 后继路线",
          "link": "/discussion/20260519-editor-kernel-selection"
        },
        {
          "text": "D-002 AI Editor 未来形态与生态设想",
          "link": "/discussion/20260519-ai-editor-future-and-ecosystem"
        }
      ]
    }
  ],
  "/issue/": [
    {
      "text": "Issue 记录",
      "items": []
    }
  ],
  "/reference/": [
    {
      "text": "参考手册",
      "items": [
        {
          "text": "R-001 Lexical AI Editor API Reference",
          "link": "/reference/20260519-api-reference"
        },
        {
          "text": "R-002 Lexical AI Editor Usage Examples",
          "link": "/reference/20260519-usage-examples"
        },
        {
          "text": "R-003 Playground 用例指南",
          "link": "/reference/20260519-playground-guide"
        },
        {
          "text": "R-004 当前能力矩阵",
          "link": "/reference/20260519-capabilities"
        }
      ]
    }
  ],
  "/roadmap/": [
    {
      "text": "规划路线",
      "items": [
        {
          "text": "P-001 Draft 到 AI Native Editor 的渐进式重构路线图",
          "link": "/roadmap/20260519-draft-to-ai-editor-roadmap"
        },
        {
          "text": "P-002 AI Editor 全量迁移实施追踪",
          "link": "/roadmap/20260519-ai-editor-migration-tracker"
        },
        {
          "text": "P-003 Lexical AI Editor 下一阶段迭代 Backlog",
          "link": "/roadmap/20260519-next-iteration-backlog"
        }
      ]
    }
  ]
};

export const wikiNav = [
  {
    "text": "首页",
    "link": "/INDEX"
  },
  {
    "text": "架构分析",
    "link": "/architecture/20260519-ai-native-editor-architecture"
  },
  {
    "text": "技术讨论",
    "link": "/discussion/20260519-editor-kernel-selection"
  },
  {
    "text": "参考手册",
    "link": "/reference/20260519-api-reference"
  },
  {
    "text": "开发规划",
    "link": "/roadmap/20260519-draft-to-ai-editor-roadmap"
  }
];
