import { SlashCommand } from './types';

export const defaultSlashCommands: SlashCommand[] = [
  {
    id: 'mode-chat',
    label: 'Chat mode',
    action: 'set-tool-mode',
    description: 'Use the composer for a direct chat answer',
    keywords: ['ask', 'answer'],
    toolMode: 'chat',
  },
  {
    id: 'mode-agent',
    label: 'Agent mode',
    action: 'set-tool-mode',
    description: 'Prepare an agent-oriented request',
    keywords: ['run', 'task'],
    toolMode: 'agent',
  },
  {
    id: 'mode-search',
    label: 'Search mode',
    action: 'set-tool-mode',
    description: 'Route the request toward retrieval or workspace search',
    keywords: ['find', 'lookup'],
    toolMode: 'search',
  },
  {
    id: 'mode-code',
    label: 'Code mode',
    action: 'set-tool-mode',
    description: 'Frame the prompt as implementation or code review work',
    keywords: ['implement', 'review'],
    toolMode: 'code',
  },
  {
    id: 'insert-tool-chip',
    label: 'Tool chip',
    action: 'insert-tool-chip',
    description: 'Insert a structured tool hint for the current mode',
    keywords: ['tool', 'mode'],
  },
  {
    id: 'insert-artifact',
    label: 'Artifact block',
    action: 'insert-artifact-block',
    description: 'Insert an editable artifact placeholder',
    keywords: ['draft', 'document', 'output'],
  },
  {
    id: 'insert-tool-call',
    label: 'Tool-call block',
    action: 'insert-tool-call-block',
    description: 'Insert an approval-ready tool call block',
    keywords: ['approve', 'run', 'agent'],
  },
  {
    id: 'review-context',
    label: 'Review context',
    action: 'insert-text',
    description: 'Insert a compact review prompt',
    keywords: ['qa', 'risk'],
    value: 'Review the selected context and identify risks.',
  },
  {
    id: 'implementation-plan',
    label: 'Implementation plan',
    action: 'insert-text',
    description: 'Insert a planning prompt',
    keywords: ['plan', 'tasks'],
    value: 'Draft an implementation plan with concrete steps.',
  },
  {
    id: 'insert-image',
    label: 'Image block',
    action: 'insert-image-block',
    description: 'Insert an image URL as visual context',
    keywords: ['media', 'screenshot'],
  },
];
